### PR TITLE
Moving Review model, migration, factory to package.

### PR DESCRIPTION
**Pull request by phuclh**
- Add Review model
- Add Review factory
- Add Review migration
- Define model references in the config file

### CODE REVIEW

**Comment by drewroberts** [comment]
@phuclh Let's also move the Key model over to this package. That model can be destroyed later as we get into the code and refactor it.

**Review by joshtorres — APPROVED** [review]
Looks good to me

**Review by drewroberts — COMMENTED** [review]
Thank you, Phuc! 👍

**Review by drewroberts — APPROVED** [review]
Thank you, Phuc! 👍

**Pull request merged**
