### PR TITLE
Package dependencies

### PR DESCRIPTION
**Pull request by huntermontell**

### CODE REVIEW

**Comment by drewroberts** [comment]
@chx2 Could you get this PR to green for us?

**Comment by chx2** [comment]
@drewroberts I fixed the references to email in the commands, but https://github.com/tipoff/locations/pull/111 will need to approved as the email field has to be populated for these tests to pass. Otherwise the tests as they are now will need to be refactored.

**Comment by drewroberts** [comment]
@chx2 Thank you. I'll update this PR after I tag a new release on that locations package. I'll wait until I merge [your other PR](https://github.com/tipoff/locations/pull/110) there too.

**Review by drewroberts — APPROVED** [review]
Thank you! 🎳

**Pull request merged**
